application: appbfw #bunjilfw #appbfw #application: appbfw #bunjilfw
version: 1
runtime: python27
api_version: 1
threadsafe: true

builtins:
- admin_redirect: on
- appstats: on
- deferred: on
- remote_api: off

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^(.*/)?\.bak$
- ^(.*/)?.*/notused/.*$
- ^(.*/)?.*/build/.*$
- ^(.*/)?.*/source/.*$
- ^(.*/)?.*\.db$
- ^(.*/)?.*\.dist-info$
- ^(.*/)?node_modules/.*$
- ^(.*/)?assets/js/.*$
- ^(.*/)?assets/stylesheets/.*$
- ^(.*/)?webpack.config\.js
- ^(.*/)?webpack-stats\.json
- ^(.*/)?package\.json

libraries:
- name: jinja2
  version: latest
- name: markupsafe
  version: latest
- name: webob
  version: latest
- name: ssl
  version: latest
- name: pycrypto
  version: latest
- name: webapp2
  version: latest
- name: django
  version: "1.5"
- name: numpy
  version: "1.6.1"

inbound_services:
- warmup

handlers:
- url: /assets
  static_dir: assets

- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /static
  static_dir: static

- url: /.well-known/.*
  script: main.app

- url: /_ah/queue/deferred
  script: google.appengine.ext.deferred.deferred.application
  login: admin

- url: /login/google
  script: main.app
  login: required
  secure: always

- url: /obs/.*
  script: main.app
  login: optional
  secure: always
  
- url: /admin/.*
  script: main.app
  login: admin

- url: /tasks/.*
  script: main.app

- url: /.*
  script: main.app
  secure: always
  
